# Start the testnet server with the command 'docker-compose up -d'

ccoinjoin-mirror-mongodb:
  image: mongo
  ports:
    - "3500:27017" # <host port>:<container port>
  volumes:
    - ./database:/data/db
  command: mongod --smallfiles --logpath=/dev/null # -- quiet
  restart: always

ccoinjoin-mirror:
  build: .
  dockerfile: Dockerfile
  links:
    - ccoinjoin-mirror-mongodb
  ports:
    - "4001:4001"  # <host port>:<container port>
    - "4002:4002"
    - "4003:4003"
    - "5000:5000"
  volumes:
    - ./logs:/home/coinjoin/consolidating-coinjoin/logs
#    - ./keys:/home/coinjoin/consolidating-coinjoin/keys

  restart: always
